-- Business table.
CREATE TABLE IF NOT EXISTS reservation (
    id  VARCHAR(64) PRIMARY KEY,
    sku VARCHAR(64) NOT NULL
);

-- Read view maintained by the consumer.
CREATE TABLE IF NOT EXISTS reservation_view (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id VARCHAR(64) NOT NULL,
    sku            VARCHAR(64) NOT NULL
);

-- Outbox table required by aipersimmon-ddd-outbox-jdbc.
CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    trace_id    VARCHAR(128),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL
);

-- Inbox table required by aipersimmon-ddd-inbox-jdbc.
CREATE TABLE IF NOT EXISTS aipersimmon_inbox (
    message_key  VARCHAR(128) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL
);
