-- Outbox table required by aipersimmon-ddd-outbox-jdbc.
CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    source      VARCHAR(255) NOT NULL,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    subject     VARCHAR(255),
    correlation_id VARCHAR(64) NOT NULL,
    causation_id   VARCHAR(64),
    trace_id    VARCHAR(128),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL
);

-- Inbox table required by aipersimmon-ddd-inbox-jdbc (deduplicates redeliveries).
CREATE TABLE IF NOT EXISTS aipersimmon_inbox (
    message_key  VARCHAR(128) PRIMARY KEY,
    processed_at TIMESTAMP NOT NULL
);
