-- Reference DDL for the aipersimmon-ddd-outbox-mybatis-plus outbox table.
-- This file is NOT run automatically; create the table yourself (for example via
-- Flyway or Liquibase) before using the outbox. Adjust types per database
-- (for PostgreSQL use TEXT instead of CLOB, TIMESTAMPTZ instead of TIMESTAMP).
-- Same schema as the outbox-jdbc starter, so the two are interchangeable.
CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    source      VARCHAR(255) NOT NULL,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    subject     VARCHAR(255),
    correlation_id VARCHAR(64) NOT NULL,
    causation_id   VARCHAR(64),
    trace_id    VARCHAR(128),
    traceparent VARCHAR(55),
    trace_state VARCHAR(512),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    -- When the relay may next try this row. NULL means "ready now" (a fresh row); a
    -- transient failure pushes it into the future for exponential backoff so the poll
    -- skips the row until then instead of re-attempting it every second.
    next_attempt_at TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL
);

-- Speeds up the relay poll (WHERE sent = FALSE AND attempts < ?
-- AND (next_attempt_at IS NULL OR next_attempt_at <= ?) ORDER BY created_at) and the
-- cleanup scan. On PostgreSQL a partial index (... WHERE sent = false) is smaller and
-- faster. Drop the IF NOT EXISTS on databases that do not support it on CREATE INDEX
-- (e.g. MySQL).
CREATE INDEX IF NOT EXISTS idx_aipersimmon_outbox_unsent
    ON aipersimmon_outbox (sent, next_attempt_at, created_at);

-- Supports the per-aggregate ordering guard: the relay's poll excludes a row while an
-- earlier unsent event of the same subject is still backing off (a correlated NOT EXISTS
-- on subject + sent + created_at/id). Without this index that subquery would scan.
CREATE INDEX IF NOT EXISTS idx_aipersimmon_outbox_subject_order
    ON aipersimmon_outbox (subject, sent, created_at, id);

-- Dead letters: messages the relay gave up delivering — a permanent failure, or one
-- that exhausted its retries. The row is MOVED here (out of aipersimmon_outbox) in one
-- transaction, so the hot outbox table holds only live work and a spent message is kept
-- for inspection and replay rather than lost. Columns mirror the outbox row plus the
-- triage fields (attempts made, reason, the last error, when it was given up on). Not
-- purged by the outbox cleanup — retention here is an operational decision.
CREATE TABLE IF NOT EXISTS aipersimmon_dead_letter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    source      VARCHAR(255) NOT NULL,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    subject     VARCHAR(255),
    correlation_id VARCHAR(64) NOT NULL,
    causation_id   VARCHAR(64),
    trace_id    VARCHAR(128),
    traceparent VARCHAR(55),
    trace_state VARCHAR(512),
    attempts    INT          NOT NULL,
    reason      VARCHAR(32)  NOT NULL,
    last_error  CLOB,
    failed_at   TIMESTAMP    NOT NULL
);

-- Lock table backing ShedLock, which makes the scheduled relay run on a single
-- instance at a time (see OutboxRelay#relay). Required whenever the outbox starter
-- is on the classpath and a DataSource is present. The column names and types are
-- ShedLock's JDBC contract — do not rename them. TIMESTAMP is correct for
-- PostgreSQL here too (ShedLock stores UTC via usingDbTime).
CREATE TABLE IF NOT EXISTS shedlock (
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
