-- Synthetic test-only component, proves the runner discovers and migrates more than one
-- aipersimmon component and gives each its own history table.
CREATE TABLE IF NOT EXISTS aipersimmon_widget (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL
);
