-- Flyway migration (H2) for the aipersimmon-ddd outbox tables. Single source of the outbox
-- schema, shared by the -outbox-jdbc and -outbox-mybatis-plus adapters (identical structure).
-- Applied automatically by the optional aipersimmon-ddd-flyway starter (dedicated history
-- table flyway_schema_history_aipersimmon_outbox), or copy into your own Flyway/Liquibase.
CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    source      VARCHAR(255) NOT NULL,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    subject     VARCHAR(255),
    correlation_id VARCHAR(64) NOT NULL,
    causation_id   VARCHAR(64),
    trace_id    VARCHAR(128),
    traceparent VARCHAR(55),
    trace_state VARCHAR(512),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_aipersimmon_outbox_unsent
    ON aipersimmon_outbox (sent, next_attempt_at, created_at);

CREATE INDEX IF NOT EXISTS idx_aipersimmon_outbox_subject_order
    ON aipersimmon_outbox (subject, sent, created_at, id);

CREATE TABLE IF NOT EXISTS aipersimmon_dead_letter (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    source      VARCHAR(255) NOT NULL,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    subject     VARCHAR(255),
    correlation_id VARCHAR(64) NOT NULL,
    causation_id   VARCHAR(64),
    trace_id    VARCHAR(128),
    traceparent VARCHAR(55),
    trace_state VARCHAR(512),
    attempts    INT          NOT NULL,
    reason      VARCHAR(32)  NOT NULL,
    last_error  CLOB,
    failed_at   TIMESTAMP    NOT NULL
);

-- ShedLock JDBC contract table (single-instance relay). Column names/types are fixed.
CREATE TABLE IF NOT EXISTS shedlock (
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
