-- MySQL 8+ sample DDL for the durable Process Manager four-table model.
-- Sample only: apply via Flyway/Liquibase; the starter never executes it. SKIP LOCKED
-- requires MySQL 8.0+. DATETIME(3) keeps millisecond precision. Payload columns are
-- LONGTEXT: they hold base64 (~+33%), so the default 1 MiB payload.max-bytes limit would
-- overflow MySQL's 64 KB TEXT ceiling.

CREATE TABLE IF NOT EXISTS aipersimmon_process_instance (
    instance_id          VARCHAR(64)  NOT NULL,
    process_type         VARCHAR(128) NOT NULL,
    business_key         VARCHAR(128) NOT NULL,
    definition_version   VARCHAR(64)  NOT NULL,
    state_schema_version INT          NOT NULL,
    lifecycle            VARCHAR(32)  NOT NULL,
    resume_lifecycle     VARCHAR(32),
    suspension_reason    VARCHAR(512),
    suspension_source    VARCHAR(32),
    suspending_work_id   VARCHAR(96),
    business_step        VARCHAR(128) NOT NULL,
    outcome              VARCHAR(128),
    revision             BIGINT       NOT NULL,
    state_payload_type   VARCHAR(255) NOT NULL,
    state_payload        LONGTEXT     NOT NULL,
    created_at           DATETIME(3)  NOT NULL,
    updated_at           DATETIME(3)  NOT NULL,
    ended_at             DATETIME(3),
    PRIMARY KEY (instance_id),
    CONSTRAINT uq_process_instance_business UNIQUE (process_type, business_key)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS aipersimmon_process_transition (
    transition_id     VARCHAR(64)  NOT NULL,
    instance_id       VARCHAR(64)  NOT NULL,
    transition_seq    BIGINT       NOT NULL,
    input_message_id  VARCHAR(96)  NOT NULL,
    input_type        VARCHAR(255) NOT NULL,
    input_version     INT          NOT NULL,
    input_payload     LONGTEXT     NOT NULL,
    from_lifecycle    VARCHAR(32),
    to_lifecycle      VARCHAR(32)  NOT NULL,
    from_step         VARCHAR(128),
    to_step           VARCHAR(128) NOT NULL,
    decision_code     VARCHAR(128) NOT NULL,
    transition_kind   VARCHAR(48)  NOT NULL,
    correlation_id    VARCHAR(64),
    trace_id          VARCHAR(128),
    traceparent       VARCHAR(55),
    trace_state       VARCHAR(512),
    operator_id       VARCHAR(64),
    operation_reason  VARCHAR(512),
    failure           TEXT,
    created_at        DATETIME(3)  NOT NULL,
    PRIMARY KEY (transition_id),
    CONSTRAINT uq_process_transition_input UNIQUE (instance_id, input_message_id),
    KEY idx_process_transition_instance (instance_id, transition_seq)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS aipersimmon_process_effect (
    effect_id       VARCHAR(96)  NOT NULL,
    instance_id     VARCHAR(64)  NOT NULL,
    transition_id   VARCHAR(64)  NOT NULL,
    effect_index    INT          NOT NULL,
    seq             BIGINT       NOT NULL,
    effect_kind     VARCHAR(48)  NOT NULL,
    payload_type    VARCHAR(255) NOT NULL,
    payload_version INT          NOT NULL,
    payload         LONGTEXT     NOT NULL,
    message_id      VARCHAR(96)  NOT NULL,
    correlation_id  VARCHAR(64)  NOT NULL,
    causation_id    VARCHAR(64),
    trace_id        VARCHAR(128),
    traceparent     VARCHAR(55),
    trace_state     VARCHAR(512),
    status          VARCHAR(16)  NOT NULL,
    attempts        INT          NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3),
    lease_owner     VARCHAR(128),
    lease_token     VARCHAR(64),
    lease_until     DATETIME(3),
    last_error      TEXT,
    created_at      DATETIME(3)  NOT NULL,
    updated_at      DATETIME(3)  NOT NULL,
    delivered_at    DATETIME(3),
    PRIMARY KEY (effect_id),
    CONSTRAINT uq_process_effect_index UNIQUE (transition_id, effect_index),
    KEY idx_process_effect_due (status, next_attempt_at),
    KEY idx_process_effect_instance (instance_id, seq),
    KEY idx_process_effect_lease (status, lease_until)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS aipersimmon_process_deadline (
    deadline_id     VARCHAR(64)  NOT NULL,
    instance_id     VARCHAR(64)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    generation      BIGINT       NOT NULL,
    due_at          DATETIME(3)  NOT NULL,
    input_type      VARCHAR(255) NOT NULL,
    input_version   INT          NOT NULL,
    input_payload   LONGTEXT     NOT NULL,
    correlation_id  VARCHAR(64),
    causation_id    VARCHAR(64),
    trace_id        VARCHAR(128),
    traceparent     VARCHAR(55),
    trace_state     VARCHAR(512),
    status          VARCHAR(16)  NOT NULL,
    attempts        INT          NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3),
    lease_owner     VARCHAR(128),
    lease_token     VARCHAR(64),
    lease_until     DATETIME(3),
    last_error      TEXT,
    created_at      DATETIME(3)  NOT NULL,
    updated_at      DATETIME(3)  NOT NULL,
    completed_at    DATETIME(3),
    PRIMARY KEY (deadline_id),
    CONSTRAINT uq_process_deadline_generation UNIQUE (instance_id, name, generation),
    KEY idx_process_deadline_due (status, next_attempt_at, due_at),
    KEY idx_process_deadline_lease (status, lease_until)
) ENGINE = InnoDB;
