spring:
  application:
    name: s19-validation-layers
  datasource:
    url: jdbc:postgresql://localhost:18191/s19
    username: s19
    password: s19
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 18190

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
