server:
  port: 8084

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/samples?currentSchema=s3_inventory
    username: postgres
    password: postgres
  flyway:
    enabled: true
    schemas: [s3_inventory]
    default-schema: s3_inventory
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

samples:
  order-placed-topic: s3.order-placed
  stock-result-topic: s3.stock-result

logging:
  level:
    com.acme.samples: INFO
