-- Write-side tables.
CREATE TABLE IF NOT EXISTS orders (
    id     VARCHAR(64) PRIMARY KEY,
    status VARCHAR(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS stock (
    sku       VARCHAR(64) PRIMARY KEY,
    available INT         NOT NULL
);

-- Outbox table required by aipersimmon-ddd-outbox-jdbc.
CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    trace_id    VARCHAR(128),
    traceparent VARCHAR(55),
    trace_state VARCHAR(512),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL
);
