CREATE TABLE IF NOT EXISTS aipersimmon_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(64)  NOT NULL UNIQUE,
    type        VARCHAR(512) NOT NULL,
    version     INT          NOT NULL,
    payload     CLOB         NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    trace_id    VARCHAR(128),
    sent        BOOLEAN      NOT NULL DEFAULT FALSE,
    sent_at     TIMESTAMP,
    attempts    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL
);
